name: Docker Build Composite Action
description: Set up Docker Buildx, extract metadata, and build

inputs:
  docker_username:
    description: 'Docker Username'
    required: true
  docker_token:
    description: "Docker Token"
    required: true

runs:
  using: "composite"
  steps:

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker
    
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_token }}