name: Retrain MNIST Model

on:
  pull_request:
    paths:
      - 'notebook-mnist.ipynb'
      - 'mnist_model/**'
  workflow_dispatch:
    inputs:
      week:
        description: 'Which week directory to train on?'
        required: true
        default: 'week 1'
jobs:
  retrain:
    env:
      WEEK: ${{ github.event.inputs.week }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download MNIST images artifact
        uses: actions/download-artifact@v4
        with:
          name: mnist_images
          path: ./mnist_images/weeks

      - name: Unpack images
        run: |
          ls -la
          tar -xf ./mnist_images/weeks/mnist-images.tar -C /week\ 1/
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip

          pip install -r requirements.txt

          pip install notebook papermill 

      - name: Execute notebook ${{ github.event.inputs.week }}
        run: |
          papermill \
            notebook-mnist.ipynb \
            retrained.ipynb \
            --log-output
        shell: bash