name: Retrain MNIST Model

on:
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip

          pip install -r requirements.txt

          pip install notebook

      - name: Execute notebook
        run: |
          jupyter nbconvert \
            --to notebook \
            --execute notebook-mnist.ipynb \
            --ExecutePreprocessor.timeout=600 \
            --output retrained.ipynb
        shell: bash