name: Train MNIST Model Manually
# This workflow trains the MNIST model using the notebook and the images artifact.

on:
  pull_request:
    paths:
      - 'notebook-mnist.ipynb'
      - 'mnist_model/**'
  workflow_dispatch:
    inputs:
      week:
        description: 'Which week directory to train on?'
        required: true
        default: 'week 1'
jobs:
  train:
    env:
      WEEK: ${{ github.event.inputs.week }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download MNIST images artifact
        uses: actions/download-artifact@v4
        with:
          name: mnist_images
          github-token: ${{ secrets.GH_PAT }}
          run-id: 15559336158
          path: .

      - name: Unpack images
        run: |
          ls -la

          rm -f ./mnist_images/weeks/week\ 1/.gitkeep

          tar --strip-components=1 -xf mnist-images.tar.gz -C ./mnist_images/weeks/week\ 1/

          ls -la ./mnist_images/weeks/week\ 1/
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip

          pip install -r requirements.txt

          pip install notebook papermill 

      - name: Execute notebook ${{ github.event.inputs.week }}
        run: |
          papermill \
            notebook-mnist.ipynb \
            retrained.ipynb \
            --log-output
        shell: bash

      - name: Upload final model
        uses: actions/upload-artifact@v4
        with:
          name: mnist_model_production
          path: ./supported_model/mnist_model_prod.h5
